### ISSUE TITLE
Expand set of characters command can contain?

### ISSUE THREAD

**Issue by smoelius** [onatm/croon#1]
Would it be possible to allow the command contain everything up to the end of the line? The presently accepted set of character is rather restrictive.

https://github.com/onatm/croon/blob/c88b4f59894d1539210c113abeb6d8a1b31ce432/src/parser.rs#L99

Sorry, I don't know much about `nom` parsers.

**Comment by onatm** [comment]
This sounds like a great improvement. I believe you already have an implementation for it. Would you like to send a PR?

**Comment by smoelius** [comment]
Sure. Though, given my inexperience with `nom` parsers, feel free to propose changes and/or push additional commits.
